worlds:
    world: config.yml
allow_vanilla_trades: false
currency: emerald
armorer: default
butcher: default
cartographer: default
cleric: default
farmer: default
fisherman: default
fletcher: default
leatherworker: default
librarian: default
nitwit: default
shepherd: default
tool_smith: default
weapon_smith: default
all_villagers: none
