name: CustomVillageTrades
main: com.alfalfascout.CustomVillageTrades.CustomVillageTrades
version: 0.12.0
api-version: 1.13
description: "Changes villagers' trade lists to a customizable list."

commands:
    customvillagetrades:
        description: CustomVillageTrades utility command.
        usage: /customvillagetrades
        permission: customvillagetrades
        aliases: [cvt, trades]
        
permissions:
    customvillagetrades.*:
        description: Gives access to all CustomVillageTrades commands.
        children:
            customvillagetrades.reload: true
            customvillagetrades.reset: true
            customvillagetrades.make.banner: true
            customvillagetrades.make.book: true
            customvillagetrades.make.firework: true
    customvillagetrades.make.*:
        description: Gives access to all CustomVillageTrades make commands.
        children:
            customvillagetrades.make.banner: true
            customvillagetrades.make.book: true
            customvillagetrades.make.firework: true
    customvillagetrades.reload:
        description: Reloads worlds and trade trees from the config files.
        default: op
    customvillagetrades.reset:
        description: Erases all villagers from the villager file.
        default: op
    customvillagetrades.make.banner:
        description: Makes a banner.yml from the player's held banner.
        default: op
    customvillagetrades.make.book:
        description: Makes a book.yml from the player's held book.
        default: op
    customvillagetrades.make.firework:
        description: Makes a firework.yml from the player's held firework.
        default: op
